# Generated by Django 2.0.6 on 2019-06-03 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(verbose_name='Employee ID')),
                ('in_time', models.TimeField(blank=True, verbose_name='Time In')),
                ('out_time', models.TimeField(blank=True, verbose_name='Time Out')),
                ('date', models.DateField(blank=True, verbose_name='Date')),
                ('total_working_time', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(unique=True, verbose_name='Employee ID')),
                ('contact_no', models.CharField(blank=True, default=0, max_length=10, verbose_name='Contact No')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date Of Birth')),
                ('date_of_joining', models.DateField(blank=True, null=True, verbose_name='Date Of Joining')),
                ('designation', models.IntegerField(choices=[(1, 'MD'), (2, 'Project manager'), (3, 'BDE'), (4, 'HR'), (5, 'TeamLead'), (6, 'Senior developer'), (7, 'Junior developer'), (8, 'Trainee'), (9, 'QA')], default=7, verbose_name='Designation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_created', to=settings.AUTH_USER_MODEL)),
                ('teamlead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamlead', to=settings.AUTH_USER_MODEL, verbose_name='Teamlead')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
